---

- name: Create local bin directory
  become: yes
  become_user: isucon
  file:
    path: /home/isucon/local
    state: directory
    mode: '755'

# in B4-training, we assume the use of Go language to run app

- name: Download Go files
  become: yes
  become_user: isucon
  get_url:
    url: https://go.dev/dl/go1.18.4.linux-amd64.tar.gz
    dest: /tmp/golang.tar.gz
    mode: '0644'

- name: Unpack Go Lang binary
  become: yes
  become_user: isucon
  unarchive:
    src: /tmp/golang.tar.gz
    dest: /home/isucon/local
    remote_src: yes

- name: Add PATH for Go
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK go"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/go/bin:/home/isucon/go/bin:$PATH
      export GOROOT=/home/isucon/local/go

# the script uses Node to run App

- name: Download Node.js files
  become: yes
  become_user: isucon
  get_url:
    url: https://nodejs.org/dist/v16.16.0/node-v16.16.0-linux-x64.tar.xz
    dest: /tmp/nodejs.tar.xz
    mode: '0644'

- name: Unpack Node.js binary
  become: yes
  become_user: isucon
  unarchive:
    src: /tmp/nodejs.tar.xz
    dest: /home/isucon/local
    remote_src: yes

- name: Rename Node.js directory
  become: yes
  become_user: isucon
  command:
    cmd: mv node-v16.16.0-linux-x64 node
    chdir: /home/isucon/local

- name: Add PATH for Node
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Node"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/node/bin:$PATH
