---
- name: Start "isuumo.go.service"
  systemd:
    daemon_reload: "yes"
    name: "isuumo.go.service"
    state: "restarted"
    enabled: "yes"

- name: Start "nginx"
  systemd:
    daemon_reload: "yes"
    name: "nginx"
    state: "reloaded"
    enabled: "yes"

- name: Initialize isucon10
  become: yes
  become_user: isucon
  uri:
    url: http://localhost/initialize
    method: POST

- name: Copy README for trainees
  become: yes
  become_user: root
  copy:
    src: "README.md"
    dest: "/home/isucon/isuumo/"
    owner: "isucon"
    group: "isucon"
